---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"prometheus-adapter","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"prometheus-adapter"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0}},"template":{"metadata":{"labels":{"name":"prometheus-adapter"}},"spec":{"containers":[{"args":["--cert-dir=/var/run/serving-cert","--config=/etc/adapter/config.yaml","--logtostderr=true","--metrics-relist-interval=1m","--prometheus-url=http://prometheus-k8s.monitoring.svc:9090/","--secure-port=6443"],"image":"quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.0","name":"prometheus-adapter","ports":[{"containerPort":6443}],"volumeMounts":[{"mountPath":"/tmp","name":"tmpfs","readOnly":false},{"mountPath":"/var/run/serving-cert","name":"volume-serving-cert","readOnly":false},{"mountPath":"/etc/adapter","name":"config","readOnly":false}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"prometheus-adapter","volumes":[{"emptyDir":{},"name":"tmpfs"},{"emptyDir":{},"name":"volume-serving-cert"},{"configMap":{"name":"adapter-config"},"name":"config"}]}}}}
  creationTimestamp: '2020-06-23T07:20:13Z'
  generation: 1
  labels: {}
  name: prometheus-adapter
  namespace: monitoring
  resourceVersion: '49918'
  selfLink: /apis/apps/v1/namespaces/monitoring/deployments/prometheus-adapter
  uid: b801b8f2-3df5-40e0-829d-377c0db12350
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: prometheus-adapter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: prometheus-adapter
    spec:
      containers:
        - args:
            - '--cert-dir=/var/run/serving-cert'
            - '--config=/etc/adapter/config.yaml'
            - '--logtostderr=true'
            - '--metrics-relist-interval=1m'
            - '--prometheus-url=http://prometheus-k8s.monitoring.svc:9090/'
            - '--secure-port=6443'
          image: 'quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.0'
          imagePullPolicy: IfNotPresent
          name: prometheus-adapter
          ports:
            - containerPort: 6443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
            - mountPath: /var/run/serving-cert
              name: volume-serving-cert
            - mountPath: /etc/adapter
              name: config
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-adapter
      serviceAccountName: prometheus-adapter
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tmpfs
        - emptyDir: {}
          name: volume-serving-cert
        - configMap:
            defaultMode: 420
            name: adapter-config
          name: config
